import { db } from "./index";
import { users, posts, communities, marketplaceItems, businesses, messages, jobs, localRadar, threads, communityMembers, clips, stories, lives, events, hashtags, notifications } from "./schema";

export async function seedDatabase() {
  const existingUsers = await db.select().from(users);
  if (existingUsers.length > 0) {
    console.log("Database already seeded");
    return;
  }

  console.log("Seeding Kinara sovereign platform database...");

  // Users - need to insert all referenced authorIds before posts
  // Also insert additional seeded users for posts
  await db.insert(users).values([
    {
      id: "usr_brian_mwangi",
      name: "Brian Mwangi",
      handle: "brianmwangi",
      avatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      cover: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      bio: "Product Architect & Design Systems Lead. Building sovereign digital platforms across Silicon Savannah, Lagos, and Kigali. Believer in high craft, offline-first systems, and African dignity in tech.",
      role: "citizen",
      location: "Nairobi, Kenya • Kilimani Hub",
      trustScore: 98,
      verified: true,
      verificationType: "National ID + Biometric & Escrow Certified",
      followersCount: 4890,
      followingCount: 382,
      marketplaceRating: "4.98",
      skills: ["Design Systems", "Distributed Systems", "FinTech Rails", "Swahili NLP", "Kinara Core", "Product Architecture"],
      achievements: [
        { title: "Silicon Savannah 40u40", desc: "Top innovators shaping East Africa", icon: "Award" },
        { title: "M-Pesa Pioneer Fellow", desc: "100+ verified escrow transactions", icon: "ShieldCheck" },
        { title: "Pan-African Speaker", desc: "Keynote at Afrotech Kigali 2025", icon: "Mic" },
        { title: "Sovereign Builder", desc: "Top 0.1% platform contributor", icon: "Flame" },
      ],
      preferences: { persona: "citizen", lowBandwidth: false },
    },
    {
      id: "usr_amina_odhiambo",
      name: "Amina Odhiambo",
      handle: "amina_ux",
      avatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      cover: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      bio: "UX Engineer & Frontend Craft Lead. Nairobi.",
      role: "creator",
      location: "Nairobi, Kenya",
      trustScore: 97,
      verified: true,
      verificationType: "Biometric & Escrow Certified",
      followersCount: 2100,
      followingCount: 340,
      marketplaceRating: "4.96",
      skills: ["Figma", "React", "Design Tokens"],
      achievements: [],
      preferences: {},
    },
    {
      id: "usr_kofi_mensah",
      name: "Kofi Mensah",
      handle: "kofi_sound",
      avatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      cover: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      bio: "Sound Architect & Afrobeats producer. Accra.",
      role: "creator",
      location: "Accra, Ghana",
      trustScore: 96,
      verified: true,
      verificationType: "Biometric & Escrow Certified",
      followersCount: 3200,
      followingCount: 210,
      marketplaceRating: "4.94",
      skills: ["Audio Engineering", "Live Production"],
      achievements: [],
      preferences: {},
    },
    {
      id: "usr_folake_adebayo",
      name: "Folake Adebayo",
      handle: "folake_lagos",
      avatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      cover: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      bio: "FinTech Founder, Lagos. Cross-border rails.",
      role: "business",
      location: "Lagos, Nigeria",
      trustScore: 99,
      verified: true,
      verificationType: "Biometric & Escrow Certified",
      followersCount: 5400,
      followingCount: 120,
      marketplaceRating: "4.99",
      skills: ["FinTech", "Smart Contracts"],
      achievements: [],
      preferences: {},
    },
  ]);

  await db.insert(threads).values([
    { id: "th_folake", title: "Lagos-Nairobi Corridor", participants: ["usr_brian_mwangi", "usr_folake_adebayo"], type: "direct" },
    { id: "th_zuri_seller", title: "Zuri Leatherworks", participants: ["usr_brian_mwangi", "zuri_seller"], type: "marketplace" },
    { id: "th_community_silicon", title: "Silicon Savannah", participants: ["usr_brian_mwangi"], type: "community" },
  ]);

  await db.insert(posts).values([
    {
      authorId: "usr_brian_mwangi",
      authorName: "Brian Mwangi",
      authorHandle: "brianmwangi",
      authorAvatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      authorTrust: 98,
      authorVerified: true,
      content: "Why copy Silicon Valley when Africa has its own design language? We didn't need desktop-era legacy paradigms. African computing is mobile-first, community-rooted, high-trust, and hyper-local. Kinara isn't another flat white feed—it's depth, emerald resonance, and sovereign utility.",
      category: "trending",
      city: "Nairobi",
      likes: 842,
      commentsCount: 2,
      sharesCount: 184,
      mediaUrl: "https://images.pexels.com/photos/29069344/pexels-photo-29069344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      mediaType: "image",
      tags: ["SovereignTech", "AfricanDesign", "SiliconSavannah", "DesignSystems"],
      pinned: true,
    },
    {
      authorId: "usr_amina_odhiambo",
      authorName: "Amina Odhiambo",
      authorHandle: "amina_ux",
      authorAvatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorTrust: 97,
      authorVerified: true,
      content: "Just tested our low-bandwidth edge synchronization in Turkana over 2G edge networks. 12KB payload latency dropped to under 120ms with local vector indexing. Technology designed for the real continent doesn't break when you leave the city fiber ring.",
      category: "innovation",
      city: "Nairobi",
      likes: 615,
      commentsCount: 1,
      sharesCount: 93,
      mediaUrl: null,
      mediaType: "text",
      tags: ["EdgeComputing", "LowBandwidth", "KenyanEngineering", "KinaraCore"],
      pinned: false,
    },
    {
      authorId: "usr_kofi_mensah",
      authorName: "Kofi Mensah",
      authorHandle: "kofi_sound",
      authorAvatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorTrust: 96,
      authorVerified: true,
      content: "Afrobeats isn't just rhythm; it's modular engineering. Dropped a new live jam in the Pan-African Sound Community voice room. Over 400 creators dialed in across Accra, Lagos, London, and Nairobi simultaneously.",
      category: "culture",
      city: "Accra",
      likes: 529,
      commentsCount: 0,
      sharesCount: 112,
      mediaUrl: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      mediaType: "image",
      tags: ["Afrobeats", "SoundLounge", "AccraVibes", "LiveAudio"],
      pinned: false,
    },
    {
      authorId: "usr_folake_adebayo",
      authorName: "Folake Adebayo",
      authorHandle: "folake_lagos",
      authorAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorTrust: 99,
      authorVerified: true,
      content: "Cross-border settlement between Naira, Kenyan Shilling, and Rwandan Franc verified on Kinara Escrow in 3.4 seconds. No banking correspondent delays, zero hidden FX margin. Direct P2P merchant trust is the real revolution.",
      category: "business",
      city: "Lagos",
      likes: 912,
      commentsCount: 1,
      sharesCount: 247,
      mediaUrl: null,
      mediaType: "text",
      tags: ["FinTech", "PanAfricanTrade", "EscrowTrust", "LagosTech"],
      pinned: false,
    },
  ]);

  await db.insert(communities).values([
    {
      id: "silicon-savannah",
      name: "Silicon Savannah Innovators",
      slug: "silicon-savannah",
      tagline: "Nairobi's premier hub for builders, architects & deep tech founders",
      description: "Connecting over 3,400 software engineers, hardware pioneers, and fintech operators across Kenya and the East African tech corridor. Home of daily live audio standups.",
      avatar: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      banner: "https://images.pexels.com/photos/29069429/pexels-photo-29069429.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      category: "Tech & Code",
      membersCount: 3420,
      activeVoice: true,
      voiceSpeakersCount: 8,
      voiceRoomTopic: "AI Agents & Autonomous M-Pesa Micro-rails in Production",
      city: "Nairobi",
      rules: [
        "Respect intellectual property and open-source contributions",
        "High signal-to-noise: share code, architecture, or verified data",
        "Support junior builders across the continent",
        "Zero spam, aggressive pitching or unverified tokens",
      ],
      createdBy: "usr_brian_mwangi",
    },
    {
      id: "afrobeats-sound",
      name: "Pan-African Sound & Audio",
      slug: "afrobeats-sound",
      tagline: "Producers, sound architects & acoustic engineers from Lagos to Nairobi",
      description: "Where African contemporary music, sonic branding, and spatial audio intersect. Weekly masterclasses and live sample drops.",
      avatar: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      banner: "https://images.pexels.com/photos/8937358/pexels-photo-8937358.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      category: "Sound & Music",
      membersCount: 2890,
      activeVoice: true,
      voiceSpeakersCount: 5,
      voiceRoomTopic: "Amapiano x Gengetone Bass Architecture Masterclass",
      city: "Pan-African",
      rules: ["Credit producers and lyricists", "Share stems in lossless format", "Be kind"],
      createdBy: "usr_kofi_mensah",
    },
    {
      id: "agri-futures",
      name: "Agri-Futures & Climate Systems",
      slug: "agri-futures",
      tagline: "Smart irrigation, solar cold chains, and decentralized crop logistics",
      description: "Transforming smallholder productivity with satellite telemetry, drone imaging, and cooperative escrow.",
      avatar: "https://images.pexels.com/photos/32203753/pexels-photo-32203753.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      banner: "https://images.pexels.com/photos/9833514/pexels-photo-9833514.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      category: "Climate & Agriculture",
      membersCount: 1940,
      activeVoice: false,
      voiceSpeakersCount: 0,
      voiceRoomTopic: null,
      city: "Rift Valley / Kigali",
      rules: ["Practical agricultural telemetry only", "Open data sharing"],
      createdBy: "usr_brian_mwangi",
    },
    {
      id: "creatives-africa",
      name: "African Design & Typography",
      slug: "creatives-africa",
      tagline: "Modern African typography, geometric motifs & tactile interfaces",
      description: "Celebrating indigenous scripts (Ge'ez, Adlam, Tifinagh) combined with ultra-clean modern typography and spatial design.",
      avatar: "https://images.pexels.com/photos/27680730/pexels-photo-27680730.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      banner: "https://images.pexels.com/photos/39533489/pexels-photo-39533489.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      category: "Design & Arts",
      membersCount: 2150,
      activeVoice: true,
      voiceSpeakersCount: 4,
      voiceRoomTopic: "Typography Critique: Ge'ez glyphs in modern Apple/Figma style",
      city: "Addis Ababa / Nairobi",
      rules: ["Constructive critique only", "No AI image spam without process notes"],
      createdBy: "usr_brian_mwangi",
    },
  ]);

  await db.insert(communityMembers).values([
    { communityId: "silicon-savannah", userId: "usr_brian_mwangi", role: "admin" },
    { communityId: "silicon-savannah", userId: "usr_amina_odhiambo", role: "member" },
    { communityId: "afrobeats-sound", userId: "usr_kofi_mensah", role: "admin" },
  ]);

  await db.insert(marketplaceItems).values([
    {
      title: "Handcrafted Rift Valley Saddle-Leather Weekender",
      description: "Full-grain Kenyan vegetable-tanned bovine leather, brass buckles cast in Kibera foundry, hand-stitched with waxed linen cord. Lifetime warranty.",
      price: 14500,
      currency: "KES",
      category: "Craft & Fashion",
      image: "https://images.pexels.com/photos/27680730/pexels-photo-27680730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      sellerId: "usr_brian_mwangi",
      sellerName: "Zuri Leatherworks",
      sellerAvatar: "https://images.pexels.com/photos/29038453/pexels-photo-29038453.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      sellerTrustScore: 99,
      sellerVerified: true,
      city: "Nairobi",
      neighborhood: "Kilimani",
      distanceKm: "1.2",
      deliverySpeed: "Boda express: 35 mins",
      aiPriceEstimate: "Fair Value: 16,800 KES (14% below market average)",
      escrowSecured: true,
      featured: true,
      rating: "4.96",
      reviewsCount: 48,
    },
    {
      title: "Inziza Geometric Rwandan Fine Woven Wall Tapestry",
      description: "Hand-harvested sisal and sweetgrass naturally dyed using tea leaves and banana bark. Modern minimalist geometry with deep emerald and warm ochre tones.",
      price: 9200,
      currency: "KES",
      category: "Art & Decor",
      image: "https://images.pexels.com/photos/27556617/pexels-photo-27556617.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      sellerId: "usr_amina_odhiambo",
      sellerName: "Imigongo Atelier",
      sellerAvatar: "https://images.pexels.com/photos/32203753/pexels-photo-32203753.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      sellerTrustScore: 97,
      sellerVerified: true,
      city: "Nairobi",
      neighborhood: "Lavington",
      distanceKm: "2.4",
      deliverySpeed: "Same-day courier: 2 hours",
      aiPriceEstimate: "Fair Value: 10,500 KES (Artisan cooperative certified)",
      escrowSecured: true,
      featured: true,
      rating: "4.92",
      reviewsCount: 31,
    },
    {
      title: "Apple MacBook Pro 16\" M3 Pro (Space Black, 36GB, 512GB)",
      description: "Flawless condition, 44 battery cycles, Kinara hardware biometric diagnostic certified. Includes original 140W MagSafe charger and protective sleeve.",
      price: 215000,
      currency: "KES",
      category: "Electronics",
      image: "https://images.pexels.com/photos/7279329/pexels-photo-7279329.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      sellerId: "usr_brian_mwangi",
      sellerName: "Alpha Tech Hub Westlands",
      sellerAvatar: "https://images.pexels.com/photos/9490631/pexels-photo-9490631.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      sellerTrustScore: 99,
      sellerVerified: true,
      city: "Nairobi",
      neighborhood: "Westlands",
      distanceKm: "3.1",
      deliverySpeed: "Verified in-person escrow pickup / Courier",
      aiPriceEstimate: "Fair Value: 230,000 KES (Save 15,000 KES with Kinara Escrow)",
      escrowSecured: true,
      featured: true,
      rating: "5.00",
      reviewsCount: 112,
    },
    {
      title: "Solara 1500W Smart Hybrid Portable Power Station",
      description: "LiFePO4 battery with 3,500+ cycles. Dual MPPT solar controller, supports AC, USB-C 100W PD, and DC 12V outputs. Perfect for blackouts and off-grid remote studios.",
      price: 52000,
      currency: "KES",
      category: "Solar & Clean Tech",
      image: "https://images.pexels.com/photos/29069344/pexels-photo-29069344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      sellerId: "usr_kofi_mensah",
      sellerName: "Kilima Energy Systems",
      sellerAvatar: "https://images.pexels.com/photos/13222553/pexels-photo-13222553.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      sellerTrustScore: 98,
      sellerVerified: true,
      city: "Nairobi",
      neighborhood: "Industrial Area",
      distanceKm: "5.8",
      deliverySpeed: "Heavy delivery truck: Within 3 hours",
      aiPriceEstimate: "Fair Value: 58,000 KES (Factory-backed 2-yr warranty)",
      escrowSecured: true,
      featured: false,
      rating: "4.89",
      reviewsCount: 76,
    },
    {
      title: "Nyeri Peaberry Single-Origin Specialty Roast (1kg)",
      description: "Elevation 1,850m on Mount Kenya slopes. Washed process, tasting notes of blackcurrant, bergamot, and cane sugar sweetness. Roasted 48 hours ago.",
      price: 2400,
      currency: "KES",
      category: "Gourmet & Food",
      image: "https://images.pexels.com/photos/8936937/pexels-photo-8936937.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      sellerId: "usr_folake_adebayo",
      sellerName: "Kawi Roastery Kilimani",
      sellerAvatar: "https://images.pexels.com/photos/8937358/pexels-photo-8937358.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      sellerTrustScore: 100,
      sellerVerified: true,
      city: "Nairobi",
      neighborhood: "Kilimani",
      distanceKm: "0.9",
      deliverySpeed: "Boda express: 20 mins",
      aiPriceEstimate: "Fair Value: 2,600 KES (Direct trade, ethical farm payout)",
      escrowSecured: true,
      featured: false,
      rating: "4.98",
      reviewsCount: 89,
    },
  ]);

  await db.insert(businesses).values([
    {
      id: "biz_ikigai_nairobi",
      name: "Ikigai Artisan Work Lounge & Roastery",
      category: "Creative Hub & Specialty Cafe",
      banner: "https://images.pexels.com/photos/8937358/pexels-photo-8937358.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      avatar: "https://images.pexels.com/photos/8936937/pexels-photo-8936937.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      headline: "Where Nairobi's tech founders, designers & creatives converge over high-elevation Arabica.",
      bio: "Designed with natural cedar, acoustic sound dampening, fiber optic 1Gbps mesh, and quiet pod rooms for high-focus deep work. Fully integrated with Kinara Escrow for desk and studio bookings.",
      city: "Nairobi",
      neighborhood: "Westlands / General Mathenge",
      rating: "4.96",
      reviewsCount: 184,
      verified: true,
      openHours: "07:00 AM - 10:00 PM Daily",
      services: [
        { name: "Day Pass + Single-Origin Coffee", price: "KES 1,500 / day" },
        { name: "Private Acoustic Sound Pod (2 hrs)", price: "KES 2,400" },
        { name: "Executive 12-Seat Boardroom with 4K Studio", price: "KES 8,000 / hr" },
        { name: "Direct Trade Micro-lot Coffee Bag (250g)", price: "KES 950" },
      ],
      catalogCount: 16,
      monthlyTransactions: 1240,
      phone: "+254 711 982 400",
      website: "https://ikigai.ke",
      ownerId: "usr_brian_mwangi",
    },
    {
      id: "biz_mara_creative",
      name: "Mara Design & Sovereign UI Labs",
      category: "Digital Product Architecture & UI",
      banner: "https://images.pexels.com/photos/29069344/pexels-photo-29069344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      avatar: "https://images.pexels.com/photos/32203753/pexels-photo-32203753.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      headline: "Crafting world-class mobile platforms, design tokens, and tactile digital products for the continent.",
      bio: "A collective of senior design systems architects, font designers, and spatial technologists based across Nairobi, Lagos, and Kigali.",
      city: "Nairobi",
      neighborhood: "Kilimani",
      rating: "4.98",
      reviewsCount: 92,
      verified: true,
      openHours: "08:30 AM - 06:30 PM (Mon-Fri)",
      services: [
        { name: "Design System Audit & Token Architecture", price: "Custom Engagement" },
        { name: "Mobile App Tactile UI Sprint (3 Weeks)", price: "From KES 450,000" },
        { name: "African Typography Custom Font Family", price: "From KES 280,000" },
      ],
      catalogCount: 8,
      monthlyTransactions: 34,
      phone: "+254 722 550 190",
      website: "https://mara.design",
      ownerId: "usr_amina_odhiambo",
    },
  ]);

  await db.insert(messages).values([
    {
      threadId: "th_folake",
      senderId: "usr_folake_adebayo",
      senderName: "Folake Adebayo",
      senderAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      senderRole: "FinTech Founder, Lagos",
      text: "Brian, the escrow smart contract for the Lagos-Nairobi trade corridor is deployed on the testnet. Can you review the multi-sig approval flow?",
      isMe: false,
      type: "text",
      metadata: null,
    },
    {
      threadId: "th_folake",
      senderId: "usr_brian_mwangi",
      senderName: "Brian Mwangi",
      senderAvatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      senderRole: "Product Architect",
      text: "Reviewed! The timeout fallback is clean. I've sent a 15-second audio breakdown of the UI state transitions for when M-Pesa or NIBSS has network latency.",
      isMe: true,
      type: "voice",
      metadata: { duration: "0:15", waveform: [40, 65, 80, 50, 95, 70, 30, 85, 90, 60, 45, 80, 75, 55, 30] },
    },
    {
      threadId: "th_zuri_seller",
      senderId: null,
      senderName: "Zuri Leatherworks",
      senderAvatar: "https://images.pexels.com/photos/29038453/pexels-photo-29038453.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      senderRole: "Verified Artisan Seller",
      text: "Habari Brian! Your custom monogrammed Saddle-Leather Weekender is finished and packaged in dust cloth. Boda courier is on standby in Kilimani.",
      isMe: false,
      type: "offer",
      metadata: { item: "Handcrafted Saddle-Leather Weekender", price: "KES 14,500", status: "Escrow Ready" },
    },
  ]);

  await db.insert(jobs).values([
    {
      title: "Lead Design Systems Architect",
      company: "PayAfrica Technologies",
      companyLogo: "https://images.pexels.com/photos/9833512/pexels-photo-9833512.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      location: "Nairobi (Kilimani) / Remote Pan-Africa",
      type: "Full-Time",
      salary: "KES 380,000 - 520,000 / mo",
      category: "Design & UX",
      tags: ["Design Systems", "Figma Tokens", "React", "Mobile First"],
    },
    {
      title: "Senior Low-Latency Rust Engineer (Offline Edge)",
      company: "Kinara Labs",
      companyLogo: "https://images.pexels.com/photos/29069344/pexels-photo-29069344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      location: "Kigali / Nairobi / Remote",
      type: "Full-Time",
      salary: "$3,800 - $5,500 / mo",
      category: "Engineering",
      tags: ["Rust", "WASM", "Distributed DB", "Offline-First"],
    },
    {
      title: "Pan-African Growth & Community Lead",
      company: "Silicon Savannah Hub",
      companyLogo: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      location: "Nairobi (Westlands)",
      type: "Full-Time",
      salary: "KES 240,000 - 320,000 / mo",
      category: "Operations",
      tags: ["Ecosystem", "Hackathons", "Audio Rooms", "Founders"],
    },
  ]);

  await db.insert(localRadar).values([
    {
      type: "friend",
      name: "Amina Odhiambo",
      avatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      city: "Nairobi",
      neighborhood: "Kilimani",
      lat: "-1.2921",
      lng: "36.7850",
      distance: "0.4 km away",
      distanceKm: "0.4",
      details: "Working from Java House Argwings • Free for coffee until 4 PM",
      status: "Active Now",
    },
    {
      type: "business",
      name: "Ikigai Artisan Work Lounge",
      avatar: "https://images.pexels.com/photos/8936937/pexels-photo-8936937.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      city: "Nairobi",
      neighborhood: "Westlands",
      lat: "-1.2650",
      lng: "36.8040",
      distance: "2.1 km away",
      distanceKm: "2.1",
      details: "Specialty coffee roastery, 1Gbps mesh wifi, acoustic pods",
      status: "Verified Open (Quiet)",
    },
    {
      type: "event",
      name: "Silicon Savannah AI & Escrow Demo Night",
      avatar: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=200&w=280",
      city: "Nairobi",
      neighborhood: "Kilimani",
      lat: "-1.2880",
      lng: "36.7910",
      distance: "1.1 km away",
      distanceKm: "1.1",
      details: "Live demos, founder pitches, and rooftop networking. 180 RSVP'd",
      status: "Starts at 6:30 PM",
    },
    {
      type: "deal",
      name: "Kawi Roastery - 25% Off Fresh Micro-Lot",
      avatar: "https://images.pexels.com/photos/8937358/pexels-photo-8937358.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      city: "Nairobi",
      neighborhood: "Kilimani",
      lat: "-1.2910",
      lng: "36.7880",
      distance: "0.8 km away",
      distanceKm: "0.8",
      details: "Flash perk for Kinara verified members on today's roast",
      status: "Valid Today Only",
    },
    {
      type: "listing",
      name: "Handcrafted Saddle-Leather Duffel (Ready)",
      avatar: "https://images.pexels.com/photos/27680730/pexels-photo-27680730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      city: "Nairobi",
      neighborhood: "Kilimani",
      lat: "-1.2950",
      lng: "36.7820",
      distance: "1.2 km away",
      distanceKm: "1.2",
      details: "Available for instant 30-min Boda courier pickup or view in person",
      status: "In Stock (1 Left)",
    },
  ]);

  // --- ALL-IN-ONE: Clips (TikTok-style short videos) ---
  await db.insert(clips).values([
    {
      authorId: "usr_kofi_mensah",
      authorName: "Kofi Mensah",
      authorHandle: "kofi_sound",
      authorAvatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorVerified: true,
      title: "Amapiano Bass Drop — Nairobi Night",
      description: "Live from Westlands studio, 400 creators, zero latency. Afrobeats is modular engineering. 🔥 #Afrobeats #Nairobi",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      thumbnailUrl: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      sound: "Kofi Sound • Original • Afrobeats Heat",
      soundTitle: "Amapiano Heat 122 BPM",
      durationSec: 18,
      likes: 8420,
      commentsCount: 312,
      sharesCount: 540,
      bookmarksCount: 1200,
      views: 48500,
      hashtags: ["Afrobeats", "NairobiVibes", "SoundLounge", "KinaraClips"],
      city: "Nairobi",
      featured: true,
    },
    {
      authorId: "usr_amina_odhiambo",
      authorName: "Amina Odhiambo",
      authorHandle: "amina_ux",
      authorAvatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorVerified: true,
      title: "Figma to Code in 45s — Linear Speed",
      description: "Design tokens → Tailwind → Motion 60fps. No handoff. Watch the lift. ✨ #DesignSystems #MadeInKenya",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnailUrl: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      sound: "Amina UX • Original • UI Flow",
      soundTitle: "UI Flow Whisper",
      durationSec: 22,
      likes: 5210,
      commentsCount: 89,
      sharesCount: 210,
      bookmarksCount: 890,
      views: 31200,
      hashtags: ["DesignSystems", "Figma", "SiliconSavannah"],
      city: "Nairobi",
      featured: true,
    },
    {
      authorId: "usr_folake_adebayo",
      authorName: "Folake Adebayo",
      authorHandle: "folake_lagos",
      authorAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorVerified: true,
      title: "3.4s Escrow — Naira to Shilling Live",
      description: "Watch the Smart Vault lock. No correspondent. No FX margin. 3.4s Nairobi→Lagos ✅ #FinTech #Escrow",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnailUrl: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      sound: "Folake • Original • Trade Rails",
      soundTitle: "Trade Rails Beat",
      durationSec: 15,
      likes: 7340,
      commentsCount: 156,
      sharesCount: 890,
      bookmarksCount: 1100,
      views: 62000,
      hashtags: ["FinTech", "Escrow", "LagosTech", "PanAfricanTrade"],
      city: "Lagos",
      featured: true,
    },
    {
      authorId: "usr_brian_mwangi",
      authorName: "Brian Mwangi",
      authorHandle: "brianmwangi",
      authorAvatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      authorVerified: true,
      title: "Low-Bandwidth Magic — Turkana 2G",
      description: "12KB payload, 120ms, local vectors. Real continent, real tech. 🌍 #Edge #KenyanEngineering",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
      thumbnailUrl: "https://images.pexels.com/photos/29069344/pexels-photo-29069344.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      sound: "Brian Mwangi • Original • Edge Sync",
      soundTitle: "Edge Sync Pulse",
      durationSec: 19,
      likes: 4120,
      commentsCount: 67,
      sharesCount: 180,
      bookmarksCount: 540,
      views: 28400,
      hashtags: ["EdgeComputing", "KinaraCore", "LowBandwidth"],
      city: "Nairobi",
      featured: false,
    },
    {
      authorId: "usr_amina_odhiambo",
      authorName: "Amina Odhiambo",
      authorHandle: "amina_ux",
      authorAvatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      authorVerified: true,
      title: "Ge'ez Glyphs × Modern UI — Addis",
      description: "Indigenous scripts meet Figma clean. Heritage is not legacy. #Typography #AddisAbaba",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
      thumbnailUrl: "https://images.pexels.com/photos/27680730/pexels-photo-27680730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      sound: "Mara Labs • Original • Type System",
      soundTitle: "Ge'ez Flow",
      durationSec: 16,
      likes: 2890,
      commentsCount: 44,
      sharesCount: 98,
      bookmarksCount: 410,
      views: 17600,
      hashtags: ["Typography", "AddisAbaba", "Design"],
      city: "Addis Ababa",
      featured: false,
    },
  ]);

  // Stories (24h ephemeral)
  const now = new Date();
  await db.insert(stories).values([
    {
      authorId: "usr_brian_mwangi",
      authorName: "Brian Mwangi",
      authorHandle: "brianmwangi",
      authorAvatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaUrl: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaType: "image",
      caption: "Kilimani sunrise standup ☀️ Shipping today",
      expiresAt: new Date(now.getTime() + 22 * 3600 * 1000),
      viewedBy: [],
    },
    {
      authorId: "usr_amina_odhiambo",
      authorName: "Amina Odhiambo",
      authorHandle: "amina_ux",
      authorAvatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaUrl: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaType: "image",
      caption: "New Figma tokens dropped 🎨",
      expiresAt: new Date(now.getTime() + 18 * 3600 * 1000),
      viewedBy: [],
    },
    {
      authorId: "usr_kofi_mensah",
      authorName: "Kofi Mensah",
      authorHandle: "kofi_sound",
      authorAvatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaUrl: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaType: "image",
      caption: "Accra studio night — Afrobeats heat 🔥",
      expiresAt: new Date(now.getTime() + 10 * 3600 * 1000),
      viewedBy: [],
    },
    {
      authorId: "usr_folake_adebayo",
      authorName: "Folake Adebayo",
      authorHandle: "folake_lagos",
      authorAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      mediaUrl: "https://images.pexels.com/photos/27680730/pexels-photo-27680730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      mediaType: "image",
      caption: "Lagos trade corridor live ✅",
      expiresAt: new Date(now.getTime() + 8 * 3600 * 1000),
      viewedBy: [],
    },
  ]);

  // Lives
  await db.insert(lives).values([
    {
      hostId: "usr_brian_mwangi",
      hostName: "Brian Mwangi",
      hostHandle: "brianmwangi",
      hostAvatar: "https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      title: "Sovereign Design Review — Live Crit",
      category: "Design & Tech",
      description: "Live teardown of Kinara tokens, motion 60fps, and low-bandwidth polish. Join stage.",
      thumbnail: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      status: "live",
      viewersCount: 342,
      likes: 1280,
    },
    {
      hostId: "usr_kofi_mensah",
      hostName: "Kofi Mensah",
      hostHandle: "kofi_sound",
      hostAvatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      title: "Afrobeats Lab — Build a Hook Live",
      category: "Music",
      description: "From 0 to hook in 30 mins. Amapiano bass + Gengetone drums.",
      thumbnail: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      status: "live",
      viewersCount: 892,
      likes: 3400,
    },
    {
      hostId: "usr_folake_adebayo",
      hostName: "Folake Adebayo",
      hostHandle: "folake_lagos",
      hostAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      title: "Trade Rails Q&A — Escrow Deep Dive",
      category: "FinTech",
      description: "M-Pesa + NIBSS + MoMo cross-border in 3.4s. Ask anything.",
      thumbnail: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      status: "live",
      viewersCount: 210,
      likes: 890,
    },
  ]);

  // Events
  await db.insert(events).values([
    {
      id: "evt_savannah_demo_night",
      title: "Silicon Savannah AI & Escrow Demo Night",
      description: "Live demos, founder pitches, rooftop networking. 180 RSVP'd. Kilimani Hub rooftop. DJs after.",
      banner: "https://images.pexels.com/photos/29069329/pexels-photo-29069329.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      location: "Kilimani Hub Rooftop, Nairobi",
      city: "Nairobi",
      category: "Tech & Code",
      startAt: new Date(now.getTime() + 2 * 24 * 3600 * 1000),
      endAt: new Date(now.getTime() + 2 * 24 * 3600 * 1000 + 3 * 3600 * 1000),
      organizerId: "usr_brian_mwangi",
      attendeesCount: 180,
      maxAttendees: 250,
      price: 0,
    },
    {
      id: "evt_beats_lab_lagos",
      title: "Pan-African Sound Lab — Lagos",
      description: "Two-day beat camp with Kofi + friends. Bring stems, leave with heat.",
      banner: "https://images.pexels.com/photos/5332445/pexels-photo-5332445.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      location: "Yaba Creative Hub, Lagos",
      city: "Lagos",
      category: "Sound & Music",
      startAt: new Date(now.getTime() + 5 * 24 * 3600 * 1000),
      endAt: new Date(now.getTime() + 7 * 24 * 3600 * 1000),
      organizerId: "usr_kofi_mensah",
      attendeesCount: 89,
      maxAttendees: 120,
      price: 5000,
    },
  ]);

  // Hashtags trending
  await db.insert(hashtags).values([
    { tag: "KinaraClips", count: 1240, trendingScore: 9800, category: "general" },
    { tag: "Afrobeats", count: 892, trendingScore: 8400, category: "music" },
    { tag: "SiliconSavannah", count: 740, trendingScore: 7200, category: "tech" },
    { tag: "DesignSystems", count: 421, trendingScore: 6100, category: "design" },
    { tag: "Escrow", count: 540, trendingScore: 5900, category: "fintech" },
    { tag: "NairobiVibes", count: 310, trendingScore: 4800, category: "city" },
  ]);

  // Notifications for Brian
  await db.insert(notifications).values([
    {
      userId: "usr_brian_mwangi",
      actorId: "usr_kofi_mensah",
      actorName: "Kofi Mensah",
      actorAvatar: "https://images.pexels.com/photos/15283143/pexels-photo-15283143.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      type: "like",
      entityType: "clip",
      entityId: "1",
      message: "Kofi liked your clip • Amapiano Bass Drop",
      read: false,
    },
    {
      userId: "usr_brian_mwangi",
      actorId: "usr_folake_adebayo",
      actorName: "Folake Adebayo",
      actorAvatar: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      type: "live",
      entityType: "live",
      entityId: "live_soon",
      message: "Folake is live: Trade Rails Q&A — Escrow Deep Dive",
      read: false,
    },
    {
      userId: "usr_brian_mwangi",
      actorId: "usr_amina_odhiambo",
      actorName: "Amina Odhiambo",
      actorAvatar: "https://images.pexels.com/photos/5999894/pexels-photo-5999894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      type: "comment",
      entityType: "post",
      entityId: "1",
      message: "Amina commented: This Figma flow is 🔥",
      read: true,
    },
  ]);

  console.log("Database seeded successfully with Kinara sovereign platform data!");
}
